create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  product_id text not null unique,
  product_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  email text not null,
  address text not null,
  total numeric(12,2) not null,
  status text not null default 'Confirmado',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null
);

alter table public.favorites enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "cp5 favorites demo select"
on public.favorites for select
using (true);

create policy "cp5 favorites demo insert"
on public.favorites for insert
with check (true);

create policy "cp5 favorites demo update"
on public.favorites for update
using (true)
with check (true);

create policy "cp5 favorites demo delete"
on public.favorites for delete
using (true);

create policy "cp5 orders demo insert"
on public.orders for insert
with check (true);

create policy "cp5 orders demo select"
on public.orders for select
using (true);

create policy "cp5 order items demo insert"
on public.order_items for insert
with check (true);

create policy "cp5 order items demo select"
on public.order_items for select
using (true);
