-- Catálogo fictício VoltTech para demonstração acadêmica. Fotos ilustrativas.
begin;
insert into public.categories(id,name,slug,icon,description) values
('celular','Celular','celular','smartphone','Para se comunicar, fotografar e resolver o dia.'),
('notebook','Notebook','notebook','laptop','Para estudar, trabalhar e criar.'),
('fone','Fone','fone','headphones','Para ouvir com conforto em qualquer rotina.'),
('tablet','Tablet','tablet','tablet','Leitura, anotações e entretenimento.'),
('acessorios','Acessórios','acessorios','cable','Pequenas escolhas que facilitam sua rotina.')
on conflict(id) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-pocket','celular','Volt Pocket','volt-pocket','VoltTech','O essencial, sem pesar no bolso.','Mensagens, chamadas e vídeos com simplicidade.',899,1099,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-pocket','O essencial, sem pesar no bolso.',array['Uso básico','Redes sociais'],array['Jogos exigentes','Fotografia profissional'],'Abre os aplicativos do dia a dia; pode demorar com muitos abertos.','Boa autonomia para uma rotina leve; jogos gastam mais.','Tela ampla para ler mensagens e assistir a vídeos.',array['Preço acessível','Uso simples'],array['Câmera simples à noite'],'Mensagens, chamadas e vídeos com simplicidade.','Para quem procura uso básico, redes sociais.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-pocket','Uso básico',5),('volt-pocket','Redes sociais',4),('volt-pocket','Fotos',2),('volt-pocket','Trabalho',3),('volt-pocket','Jogos',1),('volt-pocket','Bateria longa',4),('volt-pocket','Bateria',4),('volt-pocket','Câmera',2),('volt-pocket','Tela',3),('volt-pocket','Desempenho',2),('volt-pocket','Durabilidade',3),('volt-pocket','Portabilidade',4) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-pocket','Armazenamento','128 GB',0),('volt-pocket','Memória','4 GB',1),('volt-pocket','Tela','6,5 polegadas',2),('volt-pocket','Bateria','5.000 mAh',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-photo','celular','Volt Photo','volt-photo','VoltTech','Guarde seus melhores momentos.','Boa escolha para fotos de viagens e redes sociais.',2199,2499,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-photo','Guarde seus melhores momentos.',array['Fotos','Redes sociais'],array['Jogos no máximo'],'Alterna entre redes sociais, mapas e mensagens com fluidez.','Acompanha um dia de uso moderado, dependendo do brilho e da câmera.','Cores vivas para ver suas fotos com clareza.',array['Fotos detalhadas de dia','Tela com cores vivas'],array['Fotografar por muito tempo consome bateria'],'Boa escolha para fotos de viagens e redes sociais.','Para quem procura fotos, redes sociais.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-photo','Uso básico',5),('volt-photo','Redes sociais',5),('volt-photo','Fotos',5),('volt-photo','Trabalho',4),('volt-photo','Jogos',3),('volt-photo','Bateria longa',3),('volt-photo','Bateria',3),('volt-photo','Câmera',5),('volt-photo','Tela',5),('volt-photo','Desempenho',4),('volt-photo','Durabilidade',3),('volt-photo','Portabilidade',4) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-photo','Armazenamento','256 GB',0),('volt-photo','Memória','8 GB',1),('volt-photo','Câmera principal','50 MP',2),('volt-photo','Tela','6,4 polegadas OLED',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-endurance','celular','Volt Endurance','volt-endurance','VoltTech','Mais tempo longe da tomada.','Para quem passa o dia fora e precisa continuar conectado.',1599,null,'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-endurance','Mais tempo longe da tomada.',array['Bateria longa','Trabalho'],array['Fotos profissionais'],'Responde bem a chamadas, e-mails, mapas e aplicativos de trabalho.','Bateria maior para rotinas longas; autonomia varia com o uso.','Boa leitura em ambientes internos; sol forte exige mais brilho.',array['Bateria generosa','Espaço para aplicativos'],array['Mais pesado que modelos compactos'],'Para quem passa o dia fora e precisa continuar conectado.','Para quem procura bateria longa, trabalho.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-endurance','Uso básico',5),('volt-endurance','Redes sociais',4),('volt-endurance','Fotos',3),('volt-endurance','Trabalho',5),('volt-endurance','Jogos',2),('volt-endurance','Bateria longa',5),('volt-endurance','Bateria',5),('volt-endurance','Câmera',3),('volt-endurance','Tela',3),('volt-endurance','Desempenho',3),('volt-endurance','Durabilidade',4),('volt-endurance','Portabilidade',2) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-endurance','Armazenamento','256 GB',0),('volt-endurance','Memória','6 GB',1),('volt-endurance','Bateria','6.000 mAh',2),('volt-endurance','Tela','6,7 polegadas',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-book-study','notebook','Volt Book Study','volt-book-study','VoltTech','Seu parceiro de faculdade.','Leve para levar à aula e rápido para trabalhos e pesquisas.',2499,2799,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-book-study','Seu parceiro de faculdade.',array['Faculdade','Uso básico','Trabalho'],array['Jogos pesados','Edição profissional de vídeo'],'Documentos, aulas online e navegação funcionam bem; evite muitos programas pesados juntos.','Boa para algumas aulas longe da tomada; videochamadas reduzem a duração.','Confortável para textos e planilhas; não é voltada a edição de cores.',array['Fácil de transportar','Armazenamento rápido'],array['Memória limitada para projetos grandes'],'Leve para levar à aula e rápido para trabalhos e pesquisas.','Para quem procura faculdade, uso básico, trabalho.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-book-study','Faculdade',5),('volt-book-study','Trabalho',4),('volt-book-study','Programação',3),('volt-book-study','Jogos',1),('volt-book-study','Edição de vídeo/foto',2),('volt-book-study','Uso básico',5),('volt-book-study','Bateria',4),('volt-book-study','Tela',3),('volt-book-study','Desempenho',3),('volt-book-study','Durabilidade',3),('volt-book-study','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-book-study','Memória','8 GB',0),('volt-book-study','Armazenamento','256 GB SSD',1),('volt-book-study','Tela','14 polegadas Full HD',2),('volt-book-study','Peso','1,4 kg',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-book-work','notebook','Volt Book Work','volt-book-work','VoltTech','Trabalhe com vários programas abertos.','Equilíbrio para trabalho, faculdade e programação.',3999,4499,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-book-work','Trabalhe com vários programas abertos.',array['Trabalho','Programação','Faculdade'],array['Jogos com gráficos no máximo'],'Abre muitas abas e ferramentas de trabalho ao mesmo tempo sem tanta espera.','Boa para mobilidade; tarefas intensas pedem uma tomada por perto.','Tela nítida que ajuda a organizar janelas e ler código.',array['Bom para multitarefa','Armazenamento espaçoso'],array['Sem placa de vídeo dedicada'],'Equilíbrio para trabalho, faculdade e programação.','Para quem procura trabalho, programação, faculdade.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-book-work','Faculdade',5),('volt-book-work','Trabalho',5),('volt-book-work','Programação',5),('volt-book-work','Jogos',2),('volt-book-work','Edição de vídeo/foto',3),('volt-book-work','Uso básico',5),('volt-book-work','Bateria',4),('volt-book-work','Tela',4),('volt-book-work','Desempenho',4),('volt-book-work','Durabilidade',4),('volt-book-work','Portabilidade',4) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-book-work','Memória','16 GB',0),('volt-book-work','Armazenamento','512 GB SSD',1),('volt-book-work','Tela','15,6 polegadas Full HD',2),('volt-book-work','Peso','1,7 kg',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-book-play','notebook','Volt Book Play','volt-book-play','VoltTech','Potência para jogar e criar.','Para jogos, edição e projetos que exigem mais desempenho.',5999,6599,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-book-play','Potência para jogar e criar.',array['Jogos','Edição de vídeo/foto','Programação'],array['Quem só navega e quer economizar'],'Placa de vídeo dedicada ajuda em jogos e edição; desempenho depende de cada programa.','Jogos consomem bastante energia: use na tomada para maior desempenho.','Movimentos mais suaves em jogos e boa área para editar.',array['Mais força para tarefas pesadas','Tela fluida'],array['Mais pesado','Ventoinhas audíveis em jogos'],'Para jogos, edição e projetos que exigem mais desempenho.','Para quem procura jogos, edição de vídeo/foto, programação.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-book-play','Faculdade',4),('volt-book-play','Trabalho',5),('volt-book-play','Programação',5),('volt-book-play','Jogos',5),('volt-book-play','Edição de vídeo/foto',5),('volt-book-play','Uso básico',5),('volt-book-play','Bateria',2),('volt-book-play','Tela',5),('volt-book-play','Desempenho',5),('volt-book-play','Durabilidade',4),('volt-book-play','Portabilidade',2) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-book-play','Memória','16 GB',0),('volt-book-play','Armazenamento','1 TB SSD',1),('volt-book-play','Tela','15,6 polegadas · 144 Hz',2),('volt-book-play','Vídeo','Placa dedicada · 6 GB',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-buds-go','fone','Volt Buds Go','volt-buds-go','VoltTech','Sua trilha sonora no caminho.','Fones compactos para música e transporte.',149,null,'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-buds-go','Sua trilha sonora no caminho.',array['Uso cotidiano','Transporte','Música'],array['Jogos competitivos'],'Som equilibrado para músicas e podcasts; conexão sem fio pode ter atraso em jogos.','Estojo recarrega os fones entre os trajetos.','Sem tela; controles por toque.',array['Cabe no bolso','Sem fios'],array['Não possui cancelamento ativo de ruído'],'Fones compactos para música e transporte.','Para quem procura uso cotidiano, transporte, música.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-buds-go','Transporte',4),('volt-buds-go','Academia',3),('volt-buds-go','Trabalho/reuniões',3),('volt-buds-go','Música',4),('volt-buds-go','Jogos',2),('volt-buds-go','Uso cotidiano',5),('volt-buds-go','Bateria',3),('volt-buds-go','Desempenho',3),('volt-buds-go','Durabilidade',3),('volt-buds-go','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-buds-go','Conexão','Bluetooth',0),('volt-buds-go','Formato','Intra-auricular',1),('volt-buds-go','Autonomia estimada','5 horas por carga',2),('volt-buds-go','Microfone','Integrado',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-silence','fone','Volt Silence','volt-silence','VoltTech','Menos barulho, mais concentração.','Ajuda a reduzir o ruído constante no transporte e no trabalho.',599,699,'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-silence','Menos barulho, mais concentração.',array['Transporte','Trabalho/reuniões','Música'],array['Treinos intensos'],'Voz e música ficam mais fáceis de ouvir com redução de ruídos contínuos.','Várias sessões de uso por carga; cancelamento ligado reduz a autonomia.','Sem tela; botões físicos fáceis de encontrar.',array['Redução ativa de ruído','Conforto para trabalhar'],array['Não elimina todas as vozes ao redor','Ocupa mais espaço'],'Ajuda a reduzir o ruído constante no transporte e no trabalho.','Para quem procura transporte, trabalho/reuniões, música.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-silence','Transporte',5),('volt-silence','Academia',1),('volt-silence','Trabalho/reuniões',5),('volt-silence','Música',5),('volt-silence','Jogos',3),('volt-silence','Uso cotidiano',4),('volt-silence','Bateria',5),('volt-silence','Desempenho',5),('volt-silence','Durabilidade',4),('volt-silence','Portabilidade',3) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-silence','Conexão','Bluetooth e cabo',0),('volt-silence','Formato','Over-ear',1),('volt-silence','Recurso','Cancelamento ativo de ruído',2),('volt-silence','Autonomia estimada','30 horas',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-buds-move','fone','Volt Buds Move','volt-buds-move','VoltTech','Acompanhe seu ritmo.','Encaixe firme para caminhadas e exercícios.',299,349,'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-buds-move','Acompanhe seu ritmo.',array['Academia','Uso cotidiano'],array['Natação'],'Músicas e podcasts acompanham o treino com controles simples.','Estojo oferece recargas extras durante a semana, conforme o uso.','Sem tela; comandos nos fones.',array['Encaixe com suporte','Resiste a respingos'],array['Não pode ser submerso'],'Encaixe firme para caminhadas e exercícios.','Para quem procura academia, uso cotidiano.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-buds-move','Transporte',4),('volt-buds-move','Academia',5),('volt-buds-move','Trabalho/reuniões',3),('volt-buds-move','Música',4),('volt-buds-move','Jogos',2),('volt-buds-move','Uso cotidiano',5),('volt-buds-move','Bateria',4),('volt-buds-move','Desempenho',3),('volt-buds-move','Durabilidade',5),('volt-buds-move','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-buds-move','Conexão','Bluetooth',0),('volt-buds-move','Proteção','IPX4',1),('volt-buds-move','Autonomia estimada','7 horas por carga',2),('volt-buds-move','Encaixe','Com suporte esportivo',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-tab-read','tablet','Volt Tab Read','volt-tab-read','VoltTech','Leitura e vídeos com mais espaço.','Uma tela maior para estudar, ler e se divertir.',1099,1299,'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-tab-read','Leitura e vídeos com mais espaço.',array['Leitura','Estudos','Vídeos'],array['Desenho profissional','Substituir um notebook de trabalho'],'Ideal para livros, aulas e streaming; tarefas exigentes podem ficar lentas.','Boa autonomia para leitura com brilho moderado.','Mais confortável que um celular para ler PDFs.',array['Tela ampla','Bom para leitura'],array['Caneta ativa não incluída'],'Uma tela maior para estudar, ler e se divertir.','Para quem procura leitura, estudos, vídeos.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-tab-read','Leitura',5),('volt-tab-read','Estudos',4),('volt-tab-read','Vídeos',4),('volt-tab-read','Desenho',2),('volt-tab-read','Trabalho',2),('volt-tab-read','Jogos',2),('volt-tab-read','Bateria',4),('volt-tab-read','Tela',4),('volt-tab-read','Desempenho',2),('volt-tab-read','Durabilidade',3),('volt-tab-read','Portabilidade',4) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-tab-read','Tela','10,1 polegadas',0),('volt-tab-read','Memória','4 GB',1),('volt-tab-read','Armazenamento','64 GB',2),('volt-tab-read','Conexão','Wi-Fi',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-tab-note','tablet','Volt Tab Note','volt-tab-note','VoltTech','Suas ideias, direto na tela.','Anotações e desenhos para quem aprende criando.',2399,2699,'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-tab-note','Suas ideias, direto na tela.',array['Estudos','Desenho','Trabalho'],array['Programas exclusivos de computador'],'Abre anotações, PDFs e aulas lado a lado com boa fluidez.','Boa para estudar; vídeo e brilho alto exigem mais recargas.','Tela com boa definição e suporte à caneta.',array['Caneta incluída','Bom para anotações'],array['Teclado vendido separadamente'],'Anotações e desenhos para quem aprende criando.','Para quem procura estudos, desenho, trabalho.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-tab-note','Leitura',5),('volt-tab-note','Estudos',5),('volt-tab-note','Vídeos',5),('volt-tab-note','Desenho',5),('volt-tab-note','Trabalho',4),('volt-tab-note','Jogos',3),('volt-tab-note','Bateria',4),('volt-tab-note','Tela',5),('volt-tab-note','Desempenho',4),('volt-tab-note','Durabilidade',4),('volt-tab-note','Portabilidade',4) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-tab-note','Tela','11 polegadas',0),('volt-tab-note','Memória','8 GB',1),('volt-tab-note','Armazenamento','128 GB',2),('volt-tab-note','Caneta','Incluída',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-tab-mini','tablet','Volt Tab Mini','volt-tab-mini','VoltTech','Leve sua leitura para qualquer lugar.','Compacto para transporte, livros e navegação.',1599,null,'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-tab-mini','Leve sua leitura para qualquer lugar.',array['Leitura','Vídeos'],array['Planilhas grandes'],'Responde bem a leitura, mapas e vídeos; espaço menor para trabalhar.','Boa para leituras no caminho; varia com conexão e brilho.','Tela compacta para segurar por mais tempo.',array['Cabe em bolsas pequenas','Leve'],array['Área pequena para desenhar'],'Compacto para transporte, livros e navegação.','Para quem procura leitura, vídeos.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-tab-mini','Leitura',5),('volt-tab-mini','Estudos',4),('volt-tab-mini','Vídeos',4),('volt-tab-mini','Desenho',2),('volt-tab-mini','Trabalho',3),('volt-tab-mini','Jogos',3),('volt-tab-mini','Bateria',4),('volt-tab-mini','Tela',3),('volt-tab-mini','Desempenho',3),('volt-tab-mini','Durabilidade',3),('volt-tab-mini','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-tab-mini','Tela','8,4 polegadas',0),('volt-tab-mini','Memória','6 GB',1),('volt-tab-mini','Armazenamento','128 GB',2),('volt-tab-mini','Peso','330 g',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-power','acessorios','Volt Power 20','volt-power','VoltTech','Uma reserva de energia na bolsa.','Carregador portátil para dias longe da tomada.',199,249,'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-power','Uma reserva de energia na bolsa.',array['Viagens','Carregamento'],array['Carregar notebooks de alta potência'],'Carrega dispositivos compatíveis por USB; velocidade varia com cabo e aparelho.','Reserva de energia para recarregar o celular ao longo do dia.','Indicador mostra o nível de carga.',array['Boa capacidade','Duas saídas USB'],array['Mais pesado que baterias pequenas'],'Carregador portátil para dias longe da tomada.','Para quem procura viagens, carregamento.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-power','Viagens',5),('volt-power','Carregamento',5),('volt-power','Trabalho',3),('volt-power','Organização',2),('volt-power','Bateria',5),('volt-power','Desempenho',4),('volt-power','Durabilidade',4),('volt-power','Portabilidade',3) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-power','Capacidade','20.000 mAh',0),('volt-power','Potência máxima','20 W',1),('volt-power','Conexões','USB-A e USB-C',2),('volt-power','Peso','350 g',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-hub','acessorios','Volt Hub Connect','volt-hub','VoltTech','Mais conexões na sua mesa.','Conecte periféricos e uma tela em uma porta compatível.',249,null,'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-hub','Mais conexões na sua mesa.',array['Trabalho','Organização'],array['Aparelhos sem USB-C compatível com vídeo'],'Facilita ligar mouse, teclado e monitor; confira a compatibilidade do computador.','Usa energia do aparelho; não possui bateria própria.','Saída para monitor em computadores compatíveis.',array['Várias portas','Fácil de transportar'],array['Vídeo depende de USB-C com modo DisplayPort'],'Conecte periféricos e uma tela em uma porta compatível.','Para quem procura trabalho, organização.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-hub','Viagens',4),('volt-hub','Carregamento',2),('volt-hub','Trabalho',5),('volt-hub','Organização',5),('volt-hub','Desempenho',4),('volt-hub','Durabilidade',4),('volt-hub','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-hub','Entrada','USB-C',0),('volt-hub','Saídas','HDMI e 3 USB-A',1),('volt-hub','Vídeo','Até 4K a 30 Hz',2),('volt-hub','Compatibilidade','USB-C com DisplayPort para vídeo',3) on conflict(product_id,label) do nothing;
insert into public.products(id,category_id,name,slug,brand,short_description,description,price,old_price,image_url,stock) values ('volt-mouse','acessorios','Volt Mouse Quiet','volt-mouse','VoltTech','Conforto para estudar e trabalhar.','Mouse sem fio com cliques discretos.',89,119,'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',20) on conflict(id) do nothing;
insert into public.product_explanations values ('volt-mouse','Conforto para estudar e trabalhar.',array['Trabalho','Organização'],array['Jogos competitivos'],'Preciso para navegação, documentos e planilhas.','Funciona com pilha substituível; duração depende do uso.','Sem tela; acompanha o cursor no seu computador.',array['Cliques discretos','Preço acessível'],array['Exige uma porta USB para o receptor'],'Mouse sem fio com cliques discretos.','Para quem procura trabalho, organização.') on conflict(product_id) do nothing;
insert into public.product_use_cases(product_id,use_case,score) values ('volt-mouse','Viagens',4),('volt-mouse','Carregamento',1),('volt-mouse','Trabalho',5),('volt-mouse','Organização',4),('volt-mouse','Desempenho',3),('volt-mouse','Durabilidade',3),('volt-mouse','Portabilidade',5) on conflict(product_id,use_case) do nothing;
insert into public.product_specs(product_id,label,value,sort_order) values ('volt-mouse','Conexão','Receptor USB 2,4 GHz',0),('volt-mouse','Alimentação','1 pilha AA',1),('volt-mouse','Botões','3',2),('volt-mouse','Sensor','Óptico',3) on conflict(product_id,label) do nothing;
commit;
